echo "g++ -Wfatal-errors -Wall -fdiagnostics-color=always -std=c++20 -o "obj/default/src/file.o" -c "src/file.cpp""
mkdir -p "obj/default/src/"
g++ -Wfatal-errors -Wall -fdiagnostics-color=always -std=c++20 -o "obj/default/src/file.o" -c "src/file.cpp"
echo "g++ -Wfatal-errors -Wall -fdiagnostics-color=always -std=c++20 -o "obj/default/src/utility/cmd.o" -c "src/utility/cmd.cpp""
mkdir -p "obj/default/src/utility/"
g++ -Wfatal-errors -Wall -fdiagnostics-color=always -std=c++20 -o "obj/default/src/utility/cmd.o" -c "src/utility/cmd.cpp"
echo "g++ -Wfatal-errors -Wall -fdiagnostics-color=always -std=c++20 -o "obj/default/src/tokenizer/matcher.o" -c "src/tokenizer/matcher.cpp""
mkdir -p "obj/default/src/tokenizer/"
g++ -Wfatal-errors -Wall -fdiagnostics-color=always -std=c++20 -o "obj/default/src/tokenizer/matcher.o" -c "src/tokenizer/matcher.cpp"
echo "g++ -Wfatal-errors -Wall -fdiagnostics-color=always -std=c++20 -o "obj/default/src/tokenizer/tokenizer.o" -c "src/tokenizer/tokenizer.cpp""
mkdir -p "obj/default/src/tokenizer/"
g++ -Wfatal-errors -Wall -fdiagnostics-color=always -std=c++20 -o "obj/default/src/tokenizer/tokenizer.o" -c "src/tokenizer/tokenizer.cpp"
echo "g++ -Wfatal-errors -Wall -fdiagnostics-color=always -std=c++20 -o "obj/default/src/tokenizer/parse_context.o" -c "src/tokenizer/parse_context.cpp""
mkdir -p "obj/default/src/tokenizer/"
g++ -Wfatal-errors -Wall -fdiagnostics-color=always -std=c++20 -o "obj/default/src/tokenizer/parse_context.o" -c "src/tokenizer/parse_context.cpp"
echo "g++ -Wfatal-errors -Wall -fdiagnostics-color=always -std=c++20 -o "obj/default/src/dependency_tree.o" -c "src/dependency_tree.cpp""
mkdir -p "obj/default/src/"
g++ -Wfatal-errors -Wall -fdiagnostics-color=always -std=c++20 -o "obj/default/src/dependency_tree.o" -c "src/dependency_tree.cpp"
echo "g++ -Wfatal-errors -Wall -fdiagnostics-color=always -std=c++20 -o "obj/default/src/commands.o" -c "src/commands.cpp""
mkdir -p "obj/default/src/"
g++ -Wfatal-errors -Wall -fdiagnostics-color=always -std=c++20 -o "obj/default/src/commands.o" -c "src/commands.cpp"
echo "g++ -Wfatal-errors -Wall -fdiagnostics-color=always -std=c++20 -o "obj/default/src/project.o" -c "src/project.cpp""
mkdir -p "obj/default/src/"
g++ -Wfatal-errors -Wall -fdiagnostics-color=always -std=c++20 -o "obj/default/src/project.o" -c "src/project.cpp"
echo "g++ -Wfatal-errors -Wall -fdiagnostics-color=always -std=c++20 -o "obj/default/src/config.o" -c "src/config.cpp""
mkdir -p "obj/default/src/"
g++ -Wfatal-errors -Wall -fdiagnostics-color=always -std=c++20 -o "obj/default/src/config.o" -c "src/config.cpp"
echo "g++ -Wfatal-errors -Wall -fdiagnostics-color=always -std=c++20 -o "obj/default/src/programs/pkg_config.o" -c "src/programs/pkg_config.cpp""
mkdir -p "obj/default/src/programs/"
g++ -Wfatal-errors -Wall -fdiagnostics-color=always -std=c++20 -o "obj/default/src/programs/pkg_config.o" -c "src/programs/pkg_config.cpp"
echo "g++ -Wfatal-errors -Wall -fdiagnostics-color=always -std=c++20 -o "obj/default/src/programs/git.o" -c "src/programs/git.cpp""
mkdir -p "obj/default/src/programs/"
g++ -Wfatal-errors -Wall -fdiagnostics-color=always -std=c++20 -o "obj/default/src/programs/git.o" -c "src/programs/git.cpp"
echo "g++ -Wfatal-errors -Wall -fdiagnostics-color=always -std=c++20 -o "obj/default/src/main.o" -c "src/main.cpp""
mkdir -p "obj/default/src/"
g++ -Wfatal-errors -Wall -fdiagnostics-color=always -std=c++20 -o "obj/default/src/main.o" -c "src/main.cpp"
echo "g++ -Wfatal-errors -Wall -Wextra -fdiagnostics-color=always -std=c++20 -o "bin/lzbuild" "obj/default/src/file.o" "obj/default/src/utility/cmd.o" "obj/default/src/tokenizer/matcher.o" "obj/default/src/tokenizer/tokenizer.o" "obj/default/src/tokenizer/parse_context.o" "obj/default/src/dependency_tree.o" "obj/default/src/commands.o" "obj/default/src/project.o" "obj/default/src/config.o" "obj/default/src/programs/pkg_config.o" "obj/default/src/programs/git.o" "obj/default/src/main.o" -pthread"
mkdir -p "bin/lzbuild"
g++ -Wfatal-errors -Wall -Wextra -fdiagnostics-color=always -std=c++20 -o "bin/lzbuild" "obj/default/src/file.o" "obj/default/src/utility/cmd.o" "obj/default/src/tokenizer/matcher.o" "obj/default/src/tokenizer/tokenizer.o" "obj/default/src/tokenizer/parse_context.o" "obj/default/src/dependency_tree.o" "obj/default/src/commands.o" "obj/default/src/project.o" "obj/default/src/config.o" "obj/default/src/programs/pkg_config.o" "obj/default/src/programs/git.o" "obj/default/src/main.o" -pthread
